# Site settings
title: Bits N Grits 
email: contact@bitsngrits.com
description: > # this means to ignore newlines until "baseurl:"
  Based in Atlanta GA, Bits N Grits is the software consultancy of Stephen Jones, notably specializing in iOS, python, django, javascript, web scraping and startup product development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bitsngrits.com" # the base hostname & protocol for your site
twitter_username: StephenJ_Jones 
github_username: stephenjjones 

# Build settings
markdown: kramdown
